version: "3"
services:
  webserver:
    image: php-environment
    container_name: webserver-composer
    environment:
      - APACHE_RUN_USER=#501
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
